added script to CF

diff --git a/SW_EC2_instance.yaml b/SW_EC2_instance.yaml
--- a/SW_EC2_instance.yaml
+++ b/SW_EC2_instance.yaml
@@ -102,6 +102,10 @@ Resources:
                 systemctl start cfn-hup.service
         02_setup-service-watchdog:
           files:
+             "/var/log/test_service.log":
+                content: |
+                  Dec 27 00:01:30 ip-10-0-5-224 worker-tasks: [2019-12-27 00:01:30,710: ERROR/MainProcess] Error in timer: TimeoutError('Timeout reading from socket',)\nTraceback (most recent call last):\n
+                  Dec 27 00:01:30 ip-10-0-5-224 test-tasks: [2019-12-27 00:01:30,710: ERROR/MainProcess] Error in timer: TimeoutError('Timeout reading from socket',)\nTraceback (most recent call last):\n
              "/lib/systemd/system/service_watchdog.service":
                 content: |
                   [Unit]
@@ -112,16 +116,83 @@ Resources:
                   Restart=always
                   [Install]
                   WantedBy=multi-user.target
-          sources:
-            "/tmp/service_watchdog/": "https://github.com/usbulat/service_watchdog/tarball/main"
-          commands:
-            01install_service_watchdog:
-              command: |
-                tar –xvf /tmp/service_watchdog/service_watchdog.tar –C /tmp/service_watchdog/
-                mkdir -p /opt/service_watchdog
-                cp /tmp/service_watchdog/service_watchdog/service_watchdog.sh /opt/service_watchdog/
-                cp /tmp/service_watchdog/service_watchdog/service_watchdog.cfg /opt/service_watchdog/
-                cp /tmp/service_watchdog/service_watchdog/test_service.log /var/log/
+             "/opt/service_watchdog/service_watchdog.cfg":
+                content: |
+                  # Log file path to parse
+                  log_file="/var/log/test_service.log"
+                  # String to search
+                  search_string="Timeout reading from socket"
+             "/opt/service_watchdog/service_watchdog.sh":
+                content: |
+                  #!/bin/bash
+
+                  usage="$(basename "$0") [-h] [-c config_file] -- watchdog for service restart if string is found in specified log file
+
+                  where:
+                      -h  show this help text
+                      -c  config file path (default: service_watchdog.cfg)"
+
+                  # Default config path
+                  CONFIG_FILE="service_watchdog.cfg"
+
+                  while getopts ':hc:' option; do
+                    case "$option" in
+                      h) echo "$usage"
+                         exit
+                         ;;
+                      c) CONFIG_FILE=$OPTARG
+                         ;;
+                      :) printf "Missing argument for -%s\n" "$OPTARG" >&2
+                         echo "$usage" >&2
+                         exit 1
+                         ;;
+                      \?) printf "Illegal option: -%s\n" "$OPTARG" >&2
+                         echo "$usage" >&2
+                         exit 1
+                         ;;
+                    esac
+                  done
+                  shift $((OPTIND - 1))
+
+                  # Getting watchdog parameters
+                  if [ -f "$CONFIG_FILE" ]; then
+                    source $CONFIG_FILE
+                  else
+                    echo "Config file $CONFIG_FILE doesn't exist!"
+                    exit 2
+                  fi
+
+                  # If missing parameters, then exiting and logging about it
+                  if [ -z "$log_file" ]; then
+                    echo "Log file path is not specified in config file!"
+                    exit 3
+                  elif [ -z "$search_string" ]; then
+                    echo "Search string is not specified in config file!"
+                    exit 4
+                  fi
+
+                  # Checking if log file exists
+                  if [ ! -f "$log_file" ]; then
+                    echo "$log_file log file doesn't exist!"
+                    exit 5
+                  fi
+
+                  # Parsing each new log line for search string occurrence
+                  tail -n1 -f $log_file | while read l
+                    do
+                      if [[ "$l" == *"$search_string"* ]]; then
+                        SERVICE=$(echo $l | awk '{print $5}' | sed 's/.$//')
+                        # Restarting the service
+                        echo "Service $SERVICE will be restarted."
+                        systemctl restart backend@$SERVICE.service
+                        RESULT=$?
+                        if $RESULT; then
+                          echo "Service $SERVICE was restarted."
+                        else
+                          echo "Service $SERVICE restart failed!"
+                        fi
+                      fi
+                    done
             02enable_service_watchdog:
               command: |
                 systemctl enable service_watchdog.service
